### ISSUE TITLE
Open menu bug

### ISSUE THREAD

**Issue by Ed5k** [Qbox-project/qbx_towjob#4]
### Summary

If u want to get a towtruck(flatbed) from red blip in tow hq, u get an error  like this : 

### Reproduction

SCRIPT ERROR: @qbx-towjob/client/main.lua:79: No such export openMenu in resource **qb-menu^7**
[   3293859] [b2699_GTAProce]             MainThrd/ ^3> onPointInOutCb^7 (^5@qbx-towjob/client/main.lua^7:150)
[   3293859] [b2699_GTAProce]             MainThrd/ ^3> fn^7 (^5@PolyZone/ComboZone.lua^7:272)

### Expected behavior

-

### Actual behavior

-

### Last Updated

-

### Custom Resources

-

### Resource Rename

-

**Comment by artur-michalak** [comment]
probably fixed
